# Specifying docker compose version
version: latest

services:
  frontend:
    # Name of the service
    container_name: multiclock_frontend
    # Path to Dockerfile to build container from
    build: ./frontend
    # Ports to map from the host machine to the container
    ports:
      - "3000:3000"
    networks:
      - network

  backend:
    container_name: multiclock_backend
    build: ./backend
    ports:
      - "4000:3000"
    networks:
      - network

  mongo:
    container_name: multiclock_db
    # Specifying base image
    image: mongo:latest
    ports:
      - "27017:27017"
    # Save database contents in a volume so that it is not lost on container restarts
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

volumes:
  mongodb_data: {}

# Connect all containers on a single network
networks:
  network:
    driver: bridge
