services:
  frontend:
    # Name of the service
    container_name: multiclock_frontend
    # Path to Dockerfile to build container from
    build: ./frontend
    # Ports to map from the host machine to the container
    ports:
      - "80:3000"
    # Connects the service to the predefined network
    networks:
      - network
    # Creates environment variables
    environment:
      REACT_APP_CREATE_ENDPOINT: "http://localhost:3000/create"
      REACT_APP_JOIN_ENDPOINT: "http://localhost:3000/join"
      REACT_APP_GET_ENDPOINT: "http://localhost:3000/get"
      REACT_APP_SOCKET_ENDPOINT: "http://localhost:3001"

  backend:
    container_name: multiclock_backend
    build: ./backend
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - network
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      BACKEND_CONTAINER_PORT_EXPRESS: 3000
      BACKEND_CONTAINER_PORT_SOCKET: 3001

  mongo:
    container_name: multiclock_db
    # Specifies the base image
    image: mongo:latest
    ports:
      - "27017:27017"
    # Saves database contents in a volume to prevent data loss on container restarts
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

# Defines volumes used by services
volumes:
  mongodb_data: {}

# Defines a network to connect all containers
networks:
  network:
    # Specifies the driver for the network
    driver: bridge
