# Specifying Docker Compose version
version: latest

services:
  frontend:
    # Name of the service
    container_name: multiclock_frontend
    # Path to Dockerfile to build container from
    build: ./frontend
    # Ports to map from the host machine to the container
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    # Connects the service to the predefined network
    networks:
      - network
    # Loads environment variables from the specified file
    env_file:
      - .env

  backend:
    container_name: multiclock_backend
    build: ./backend
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    networks:
      - network
    env_file:
      - .env

  mongo:
    container_name: multiclock_db
    # Specifies the base image
    image: mongo:latest
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_CONTAINER_PORT}"
    # Saves database contents in a volume to prevent data loss on container restarts
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

# Defines volumes used by services
volumes:
  mongodb_data: {}

# Defines a network to connect all containers
networks:
  network:
    # Specifies the driver for the network
    driver: bridge
